video-encoding, leave file in place on error
Instead of saying it was completed, trying to do the rename, all that
noise, just complain and leave the file where it is.

I've been trying to figure out a good thing to do involving files with
spaces and also getting more options from the profile file. It's very
frustrating. I'll get there, and at least with my testing I don't want
to have to repeatedly rename files _back_ from the `complete` versions
to try again.

diff --git a/scripts/encode_videos b/scripts/encode_videos
--- a/scripts/encode_videos
+++ b/scripts/encode_videos
@@ -72,8 +72,14 @@ do
                 echo "HandBrake Encoding"
                 HandBrakeCLI $OPTIONS --optimize -i $VID -o $OUTFILE
             fi
-            mv $TOCHANGE $COMPLETED
-            echo "Completed and renamed to $COMPLETED"
+
+            if [ $? == 0 ]
+            then
+                mv $TOCHANGE $COMPLETED
+                echo "Completed and renamed to $COMPLETED"
+            else
+                echo "Error in converting $VID"
+            fi
         done
     fi
 done
